# coding: utf-8

"""
    Webhooks API

     Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage. Use webhook subscriptions to subscribe to different webhook events. 

    The version of the OpenAPI document: 0.1
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from brex_webhooks_python_sdk import schemas  # noqa: F401


class PaymentType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Only ACH, DOMESTIC_WIRE, CHEQUE, INTERNATIONAL_WIRE and BOOK_TRANSFER details can be retrieved from the Payments API.
    """


    class MetaOapg:
        enum_value_to_name = {
            "ACH": "ACH",
            "DOMESTIC_WIRE": "DOMESTIC_WIRE",
            "CHEQUE": "CHEQUE",
            "INTERNATIONAL_WIRE": "INTERNATIONAL_WIRE",
            "BOOK_TRANSFER": "BOOK_TRANSFER",
            "ACH_RETURN": "ACH_RETURN",
            "WIRE_RETURN": "WIRE_RETURN",
            "CHEQUE_RETURN": "CHEQUE_RETURN",
        }
    
    @schemas.classproperty
    def ACH(cls):
        return cls("ACH")
    
    @schemas.classproperty
    def DOMESTIC_WIRE(cls):
        return cls("DOMESTIC_WIRE")
    
    @schemas.classproperty
    def CHEQUE(cls):
        return cls("CHEQUE")
    
    @schemas.classproperty
    def INTERNATIONAL_WIRE(cls):
        return cls("INTERNATIONAL_WIRE")
    
    @schemas.classproperty
    def BOOK_TRANSFER(cls):
        return cls("BOOK_TRANSFER")
    
    @schemas.classproperty
    def ACH_RETURN(cls):
        return cls("ACH_RETURN")
    
    @schemas.classproperty
    def WIRE_RETURN(cls):
        return cls("WIRE_RETURN")
    
    @schemas.classproperty
    def CHEQUE_RETURN(cls):
        return cls("CHEQUE_RETURN")
