# coding: utf-8

"""
    Webhooks API

     Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage. Use webhook subscriptions to subscribe to different webhook events. 

    The version of the OpenAPI document: 0.1
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from brex_webhooks_python_sdk import schemas  # noqa: F401


class WebhookEventType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        enum_value_to_name = {
            "REFERRAL_CREATED": "REFERRAL_CREATED",
            "REFERRAL_ACTIVATED": "REFERRAL_ACTIVATED",
            "REFERRAL_APPLICATION_STATUS_CHANGED": "REFERRAL_APPLICATION_STATUS_CHANGED",
            "TRANSFER_PROCESSED": "TRANSFER_PROCESSED",
            "TRANSFER_FAILED": "TRANSFER_FAILED",
            "EXPENSE_PAYMENT_UPDATED": "EXPENSE_PAYMENT_UPDATED",
            "USER_UPDATED": "USER_UPDATED",
        }
    
    @schemas.classproperty
    def REFERRAL_CREATED(cls):
        return cls("REFERRAL_CREATED")
    
    @schemas.classproperty
    def REFERRAL_ACTIVATED(cls):
        return cls("REFERRAL_ACTIVATED")
    
    @schemas.classproperty
    def REFERRAL_APPLICATION_STATUS_CHANGED(cls):
        return cls("REFERRAL_APPLICATION_STATUS_CHANGED")
    
    @schemas.classproperty
    def TRANSFER_PROCESSED(cls):
        return cls("TRANSFER_PROCESSED")
    
    @schemas.classproperty
    def TRANSFER_FAILED(cls):
        return cls("TRANSFER_FAILED")
    
    @schemas.classproperty
    def EXPENSE_PAYMENT_UPDATED(cls):
        return cls("EXPENSE_PAYMENT_UPDATED")
    
    @schemas.classproperty
    def USER_UPDATED(cls):
        return cls("USER_UPDATED")
