# coding: utf-8

"""
    Webhooks API

     Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage. Use webhook subscriptions to subscribe to different webhook events. 

    The version of the OpenAPI document: 0.1
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from brex_webhooks_python_sdk import schemas  # noqa: F401


class WebhookSubscriptionsListSecretsResponse(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['WebhookSecret']:
            return WebhookSecret

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['WebhookSecret'], typing.List['WebhookSecret']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'WebhookSubscriptionsListSecretsResponse':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'WebhookSecret':
        return super().__getitem__(i)

from brex_webhooks_python_sdk.model.webhook_secret import WebhookSecret
