# coding: utf-8

"""
    Webhooks API

     Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage. Use webhook subscriptions to subscribe to different webhook events. 

    The version of the OpenAPI document: 0.1
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from brex_webhooks_python_sdk.paths.v1_webhooks_id.get import GetDetails
from brex_webhooks_python_sdk.paths.v1_webhooks.get import List
from brex_webhooks_python_sdk.paths.v1_webhooks_secrets.get import ListSecrets
from brex_webhooks_python_sdk.paths.v1_webhooks.post import RegisterEndpoint
from brex_webhooks_python_sdk.paths.v1_webhooks_id.delete import UnregisterWebhook
from brex_webhooks_python_sdk.paths.v1_webhooks_id.put import UpdateWebhook
from brex_webhooks_python_sdk.apis.tags.webhook_subscriptions_api_raw import WebhookSubscriptionsApiRaw


class WebhookSubscriptionsApi(
    GetDetails,
    List,
    ListSecrets,
    RegisterEndpoint,
    UnregisterWebhook,
    UpdateWebhook,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WebhookSubscriptionsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WebhookSubscriptionsApiRaw(api_client)
