# coding: utf-8

"""
    Webhooks API

     Brex uses webhooks to send real-time notifications when events happen in the accounts that you manage. Use webhook subscriptions to subscribe to different webhook events. 

    The version of the OpenAPI document: 0.1
    Contact: developer-access@brex.com
    Created by: https://brex.com
"""

from brex_webhooks_python_sdk.paths.v1_webhooks_id.get import GetDetailsRaw
from brex_webhooks_python_sdk.paths.v1_webhooks.get import ListRaw
from brex_webhooks_python_sdk.paths.v1_webhooks_secrets.get import ListSecretsRaw
from brex_webhooks_python_sdk.paths.v1_webhooks.post import RegisterEndpointRaw
from brex_webhooks_python_sdk.paths.v1_webhooks_id.delete import UnregisterWebhookRaw
from brex_webhooks_python_sdk.paths.v1_webhooks_id.put import UpdateWebhookRaw


class WebhookSubscriptionsApiRaw(
    GetDetailsRaw,
    ListRaw,
    ListSecretsRaw,
    RegisterEndpointRaw,
    UnregisterWebhookRaw,
    UpdateWebhookRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
